import { useEffect, useState } from "react";
import { View, Text, Pressable, StyleSheet, FlatList, ActivityIndicator } from "react-native";
import { router } from "expo-router";
import { supabase } from "@/lib/supabase";
import { theme } from "@/lib/theme";
export default function Calls(){
 const [rows,setRows]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 async function load(){if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data,error}=await supabase.from("call_sessions").select("id,caller_id,callee_id,kind,status,created_at,ended_at").or(`caller_id.eq.${user.id},callee_id.eq.${user.id}`).order("created_at",{ascending:false}).limit(100);if(error){setLoading(false);return}const ids=[...new Set((data||[]).flatMap((x:any)=>[x.caller_id,x.callee_id]))];const {data:profiles}=ids.length?await supabase.from("profiles").select("id,username,display_name").in("id",ids):{data:[]};const map=new Map((profiles||[]).map((x:any)=>[x.id,x]));setRows((data||[]).map((x:any)=>({...x,other:map.get(x.caller_id===user.id?x.callee_id:x.caller_id)})));setLoading(false)}
 useEffect(()=>{load();let ch:any;(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;ch=supabase.channel(`calls-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"call_sessions"},()=>load()).subscribe()})();return()=>{if(ch&&supabase)supabase.removeChannel(ch)}},[]);
 return <View style={s.root}><Text style={s.title}>Calls</Text>{loading?<View style={s.empty}><ActivityIndicator color={theme.purple}/></View>:<FlatList data={rows} keyExtractor={x=>x.id} contentContainerStyle={{paddingTop:18,paddingBottom:80}} ListEmptyComponent={<View style={s.empty}><Text style={s.big}>⌕</Text><Text style={s.emptyTitle}>No calls yet</Text><Text style={s.muted}>Your real voice and video call history will appear here.</Text></View>} renderItem={({item})=>{const other=item.other; return <View style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{(other?.display_name||other?.username||"U")[0]}</Text></View><View style={{flex:1}}><Text style={s.name}>{other?.display_name||other?.username||"bs.world user"}</Text><Text style={s.muted}>{item.kind==="video"?"Video":"Voice"} · {item.status} · {new Date(item.created_at).toLocaleString()}</Text></View><Text style={s.icon}>{item.kind==="video"?"🎥":"📞"}</Text></View>}}/>}<Pressable style={s.back} onPress={()=>router.replace("/home")}><Text style={s.backText}>← Back</Text></Pressable></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg,padding:22,paddingTop:58},title:{color:"#fff",fontSize:28,fontWeight:"800"},empty:{flex:1,alignItems:"center",justifyContent:"center"},big:{fontSize:55,color:theme.purple},emptyTitle:{color:"#fff",fontSize:20,fontWeight:"800",marginTop:12},muted:{color:theme.muted,textAlign:"center",marginTop:7},row:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:13,borderBottomWidth:1,borderBottomColor:theme.border},avatar:{width:48,height:48,borderRadius:16,backgroundColor:theme.card2,alignItems:"center",justifyContent:"center"},avatarText:{color:"#fff",fontWeight:"800",fontSize:18},name:{color:"#fff",fontWeight:"700"},icon:{fontSize:20},back:{position:"absolute",bottom:20,left:22},backText:{color:"#B990FF",fontWeight:"700"}});
