import { useEffect, useRef, useState } from "react";
import { View, Text, Pressable, StyleSheet, Alert } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { supabase } from "@/lib/supabase";
import { theme } from "@/lib/theme";
import { RTCPeerConnection, RTCView, mediaDevices, MediaStream, RTCSessionDescription, RTCIceCandidate } from "react-native-webrtc";

const turnUrl=process.env.EXPO_PUBLIC_TURN_URL; const turnUser=process.env.EXPO_PUBLIC_TURN_USERNAME; const turnCredential=process.env.EXPO_PUBLIC_TURN_CREDENTIAL;
const ICE:any={iceServers:[{urls:"stun:stun.l.google.com:19302"},...(turnUrl&&turnUser&&turnCredential?[{urls:turnUrl,username:turnUser,credential:turnCredential}]:[])]};
const TIERS=[{maxBitrate:250000,maxFramerate:12,scale:2},{maxBitrate:600000,maxFramerate:20,scale:1.5},{maxBitrate:1200000,maxFramerate:30,scale:1}];
export default function Call(){
 const p=useLocalSearchParams<{callId?:string;name?:string;kind?:string;incoming?:string}>(); const callId=Array.isArray(p.callId)?p.callId[0]:p.callId; const name=Array.isArray(p.name)?p.name[0]:p.name; const kind=(Array.isArray(p.kind)?p.kind[0]:p.kind)==="voice"?"voice":"video"; const incoming=(Array.isArray(p.incoming)?p.incoming[0]:p.incoming)==="1";
 const pc=useRef<RTCPeerConnection|null>(null); const channel=useRef<any>(null); const me=useRef<string|null>(null); const streamRef=useRef<MediaStream|null>(null); const pendingIce=useRef<any[]>([]); const ended=useRef(false); const tier=useRef(1);
 const pendingOffer=useRef<any>(null);
 const [stream,setStream]=useState<MediaStream|null>(null); const [remote,setRemote]=useState<MediaStream|null>(null); const [status,setStatus]=useState(incoming?"Incoming call":"Calling…"); const [muted,setMuted]=useState(false); const [camera,setCamera]=useState(kind==="video"); const [accepted,setAccepted]=useState(!incoming); const [quality,setQuality]=useState("Adaptive");
 async function sendSignal(type:string,payload:any){if(!supabase||!callId||!me.current||ended.current)return;await supabase.from("call_signals").insert({call_id:callId,sender_id:me.current,signal_type:type,payload})}
 async function setCallStatus(v:string){if(supabase&&callId)await supabase.from("call_sessions").update({status:v,...(v==="ended"?{ended_at:new Date().toISOString()}:{})}).eq("id",callId)}
 async function applyTier(n:number){const c:any=pc.current;if(!c||kind!=="video")return;const senders=c.getSenders?.()||[];const sender=senders.find((x:any)=>x.track?.kind==="video");if(!sender?.getParameters)return;try{const params=sender.getParameters();params.encodings=params.encodings?.length?params.encodings:[{}];params.encodings.forEach((e:any)=>{e.maxBitrate=TIERS[n].maxBitrate;e.maxFramerate=TIERS[n].maxFramerate;e.scaleResolutionDownBy=TIERS[n].scale});await sender.setParameters(params);tier.current=n;setQuality(n===0?"Low network":n===1?"Balanced":"High quality")}catch{}}
 async function adapt(){const c:any=pc.current;if(!c?.getStats||kind!=="video")return;try{const stats=await c.getStats();let loss=0,sent=0,rtt=0;stats.forEach((v:any)=>{if(v.type==="outbound-rtp"&&v.kind==="video"){loss+=v.packetsLost||0;sent+=v.packetsSent||0}if(v.type==="remote-inbound-rtp"&&v.kind==="video")rtt=Math.max(rtt,(v.roundTripTime||0)*1000)});const ratio=sent?loss/(sent+loss):0;let n=tier.current;if(rtt>450||ratio>.08)n=Math.max(0,n-1);else if(rtt<180&&ratio<.02)n=Math.min(2,n+1);if(n!==tier.current)await applyTier(n)}catch{}}
 async function processSignal(sig:any,connection:RTCPeerConnection){if(!sig||sig.sender_id===me.current)return;try{if(sig.signal_type==="offer"&&incoming){if(!accepted){pendingOffer.current=sig.payload;return;}await connection.setRemoteDescription(new RTCSessionDescription(sig.payload));for(const c of pendingIce.current.splice(0)){try{await connection.addIceCandidate(new RTCIceCandidate(c))}catch{}}const answer=await connection.createAnswer();await connection.setLocalDescription(answer);await sendSignal("answer",answer);await setCallStatus("accepted");setStatus("Connected")}else if(sig.signal_type==="answer"&&!incoming){await connection.setRemoteDescription(new RTCSessionDescription(sig.payload));for(const c of pendingIce.current.splice(0)){try{await connection.addIceCandidate(new RTCIceCandidate(c))}catch{}}setStatus("Connected")}else if(sig.signal_type==="ice"){if(connection.remoteDescription)await connection.addIceCandidate(new RTCIceCandidate(sig.payload));else pendingIce.current.push(sig.payload)}else if(sig.signal_type==="hangup"){await endCall(false)}}catch{}}
 useEffect(()=>{let mounted=true;let timer:any;let adaptive:any;(async()=>{if(!supabase||!callId)return;const {data:{user}}=await supabase.auth.getUser();if(!user){router.back();return}me.current=user.id;const {data:session}=await supabase.from("call_sessions").select("caller_id,callee_id,status,kind").eq("id",callId).single();if(!session){Alert.alert("Call unavailable","This call no longer exists.");router.back();return}try{const media=await mediaDevices.getUserMedia({audio:true,video:kind==="video"?{facingMode:"user",width:1280,height:720,frameRate:30}:false});if(!mounted)return;streamRef.current=media;setStream(media);const connection=new RTCPeerConnection(ICE);pc.current=connection;media.getTracks().forEach(t=>connection.addTrack(t,media));connection.ontrack=e=>{if(e.streams?.[0])setRemote(e.streams[0])};connection.onicecandidate=e=>{if(e.candidate)sendSignal("ice",e.candidate.toJSON())};connection.onconnectionstatechange=()=>{const st=connection.connectionState;if(st==="connected"){setStatus("Connected");applyTier(2)}if(st==="failed"){setStatus("Connection failed")}if(st==="disconnected")setStatus("Reconnecting…")};
 channel.current=supabase.channel(`call-${callId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"call_signals",filter:`call_id=eq.${callId}`},({new:sig}:any)=>processSignal(sig,connection)).subscribe(async(st:any)=>{if(st!=="SUBSCRIBED")return;const {data:existing}=await supabase.from("call_signals").select("*").eq("call_id",callId).order("created_at",{ascending:true});for(const sig of existing||[])await processSignal(sig,connection);if(!incoming){const offer=await connection.createOffer({});await connection.setLocalDescription(offer);await sendSignal("offer",offer)}});
 timer=setTimeout(()=>{if(!ended.current){setStatus("No answer");endCall(true)}},60000);adaptive=setInterval(adapt,3000);
 }catch(e:any){Alert.alert("Call setup failed",e?.message||"Camera/microphone permission is required.");router.back()}})();return()=>{mounted=false;clearTimeout(timer);clearInterval(adaptive);streamRef.current?.getTracks().forEach(t=>t.stop());pc.current?.close();if(channel.current&&supabase)supabase.removeChannel(channel.current)}},[callId]);
 async function accept(){setAccepted(true);setStatus("Connecting…");await setCallStatus("accepted");if(pendingOffer.current&&pc.current){await processSignal({signal_type:"offer",sender_id:"other",payload:pendingOffer.current},pc.current);pendingOffer.current=null}}; async function reject(){ended.current=true;await sendSignal("hangup",{});await setCallStatus("declined");router.back()}; async function endCall(remoteEnd=true){if(ended.current)return;ended.current=true;if(remoteEnd)await sendSignal("hangup",{});await setCallStatus("ended");streamRef.current?.getTracks().forEach(t=>t.stop());pc.current?.close();if(channel.current&&supabase)supabase.removeChannel(channel.current);router.back()}; function toggleMute(){streamRef.current?.getAudioTracks().forEach(t=>t.enabled=!t.enabled);setMuted(x=>!x)};function toggleCamera(){streamRef.current?.getVideoTracks().forEach(t=>t.enabled=!t.enabled);setCamera(x=>!x)};
 if(incoming&&!accepted)return <View style={s.root}><View style={s.incoming}><Text style={s.brand}>bs.world</Text><Text style={s.avatar}>◉</Text><Text style={s.name}>{name||"bs.world user"}</Text><Text style={s.status}>Incoming {kind} call</Text><View style={s.incomingBtns}><Pressable style={[s.big,s.decline]} onPress={reject}><Text style={s.bigText}>✕</Text></Pressable><Pressable style={[s.big,s.accept]} onPress={accept}><Text style={s.bigText}>✓</Text></Pressable></View></View></View>;
 return <View style={s.root}>{remote&&kind==="video"?<RTCView streamURL={remote.toURL()} style={s.remote} objectFit="cover"/>:<View style={s.remoteFallback}><Text style={s.avatar}>◉</Text><Text style={s.name}>{name||"bs.world user"}</Text><Text style={s.status}>{status}</Text></View>}{stream&&kind==="video"&&camera?<RTCView streamURL={stream.toURL()} style={s.local} objectFit="cover"/>:null}<View style={s.top}><Text style={s.brand}>bs.world</Text><Text style={s.kind}>{kind==="video"?`Video call · ${quality}`:"Voice call"}</Text></View><View style={s.controls}><Pressable style={s.control} onPress={toggleMute}><Text style={s.icon}>{muted?"🔇":"🎙️"}</Text></Pressable>{kind==="video"&&<Pressable style={s.control} onPress={toggleCamera}><Text style={s.icon}>{camera?"📷":"🚫"}</Text></Pressable>}<Pressable style={[s.control,s.end]} onPress={()=>endCall()}><Text style={s.icon}>☎</Text></Pressable></View></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#05071e"},remote:{...StyleSheet.absoluteFillObject},remoteFallback:{...StyleSheet.absoluteFillObject,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg},incoming:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:theme.bg},brand:{color:"#fff",fontSize:20,fontWeight:"900"},avatar:{fontSize:70,color:theme.purple},name:{color:"#fff",fontSize:22,fontWeight:"800",marginTop:14},status:{color:theme.muted,marginTop:7},top:{position:"absolute",top:55,left:22},kind:{color:theme.muted,marginTop:3},local:{position:"absolute",right:16,top:110,width:115,height:170,borderRadius:18},controls:{position:"absolute",bottom:55,left:0,right:0,flexDirection:"row",justifyContent:"center",gap:18},control:{width:62,height:62,borderRadius:31,backgroundColor:theme.card2,alignItems:"center",justifyContent:"center"},end:{backgroundColor:theme.danger},icon:{fontSize:23},incomingBtns:{flexDirection:"row",gap:45,marginTop:45},big:{width:72,height:72,borderRadius:36,alignItems:"center",justifyContent:"center"},accept:{backgroundColor:theme.success},decline:{backgroundColor:theme.danger},bigText:{color:"#fff",fontSize:28,fontWeight:"900"}});
