import { useEffect, useRef, useState } from "react";
import { View, Text, TextInput, Pressable, FlatList, StyleSheet, Alert, ActivityIndicator, Image, Linking } from "react-native";
import * as ImagePicker from "expo-image-picker";
import * as DocumentPicker from "expo-document-picker";
import { router, useLocalSearchParams } from "expo-router";
import { supabase } from "@/lib/supabase";
import { theme } from "@/lib/theme";

function MediaBubble({path,type,onOpen}:{path:string;type:string;onOpen:()=>void}){
 const [url,setUrl]=useState<string|null>(null);
 useEffect(()=>{let ok=true;(async()=>{if(type!=="image"||!supabase)return;const {data}=await supabase.storage.from("chat-media").createSignedUrl(path,3600);if(ok)setUrl(data?.signedUrl||null)})();return()=>{ok=false}},[path,type]);
 if(type==="image") return <Pressable onPress={onOpen}>{url?<Image source={{uri:url}} style={s.image}/>:<View style={[s.image,{alignItems:"center",justifyContent:"center"}]}><Text style={s.file}>Loading photo…</Text></View>}</Pressable>;
 return <Pressable onPress={onOpen}><View style={s.attachment}><Text style={s.file}>{type==="video"?"▶ Video":"📎 File"}</Text><Text style={s.fileName}>Tap to open</Text></View></Pressable>;
}

export default function Chat(){
 const p=useLocalSearchParams<{profileId?:string;name?:string;conversationId?:string}>();
 const profileId=Array.isArray(p.profileId)?p.profileId[0]:p.profileId; const name=Array.isArray(p.name)?p.name[0]:p.name;
 const [text,setText]=useState(""); const [messages,setMessages]=useState<any[]>([]); const [cid,setCid]=useState<string|null>((Array.isArray(p.conversationId)?p.conversationId[0]:p.conversationId)||null); const [loading,setLoading]=useState(true); const [typing,setTyping]=useState(false); const [me,setMe]=useState<string|null>(null); const [mediaBusy,setMediaBusy]=useState(false); const channel=useRef<any>(null); const typingTimer=useRef<any>();
 useEffect(()=>{ let active=true; (async()=>{if(!supabase){setLoading(false);return} const {data:{user}}=await supabase.auth.getUser(); if(!user){router.replace('/login');return} setMe(user.id); let id=cid; if(!id&&profileId){const {data,error}=await supabase.rpc("get_or_create_direct_conversation",{other_user:profileId}); if(error){Alert.alert("Chat setup failed",error.message);setLoading(false);return} id=data;}
  if(!id){setLoading(false);return} if(!active)return; setCid(id); const {data,error}=await supabase.from("messages").select("id,conversation_id,sender_id,body,message_type,media_url,created_at,read_at").eq("conversation_id",id).order("created_at",{ascending:true}).limit(500); if(error)Alert.alert("Messages error",error.message); else setMessages(data||[]); setLoading(false);
  channel.current=supabase.channel(`chat-${id}`,{config:{presence:{key:user.id},broadcast:{self:false}}}).on("postgres_changes",{event:"*",schema:"public",table:"messages",filter:`conversation_id=eq.${id}`},payload=>{if(payload.eventType==="INSERT")setMessages(x=>x.some(m=>m.id===payload.new.id)?x:[...x,payload.new]); if(payload.eventType==="UPDATE")setMessages(x=>x.map(m=>m.id===payload.new.id?payload.new:m));}).on("broadcast",{event:"typing"},({payload}:any)=>{if(payload?.user_id!==user.id){setTyping(!!payload.typing);}}).subscribe(); })(); return()=>{active=false;if(channel.current&&supabase)supabase.removeChannel(channel.current)} },[profileId,cid]);
 useEffect(()=>{if(!supabase||!me)return; messages.filter(m=>m.sender_id!==me&&!m.read_at).slice(-50).forEach(m=>supabase.rpc("mark_message_read",{p_message_id:m.id}));},[messages,me]);
 const broadcastTyping=(v:boolean)=>{if(channel.current)channel.current.send({type:"broadcast",event:"typing",payload:{user_id:me,typing:v}})};
 useEffect(()=>{if(!text){broadcastTyping(false);return} broadcastTyping(true); clearTimeout(typingTimer.current); typingTimer.current=setTimeout(()=>broadcastTyping(false),1200); return()=>clearTimeout(typingTimer.current)},[text]);
 async function send(body=text.trim(),type="text",mediaPath:string|null=null){if(!supabase||!cid||!me||(!body&&!mediaPath))return; const {data,error}=await supabase.from("messages").insert({conversation_id:cid,sender_id:me,body:body||null,message_type:type,media_url:mediaPath}).select().single(); if(error)Alert.alert("Message failed",error.message); else {setText("");broadcastTyping(false);if(data)setMessages(x=>x.some(m=>m.id===data.id)?x:[...x,data]);}}
 async function pickImage(){const r=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!r.granted)return Alert.alert("Permission required","Allow photo access to send media.");const x=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images","videos"] as any,quality:0.85});if(x.canceled)return;const a=x.assets[0];await uploadUri(a.uri,a.mimeType||"image/jpeg",a.fileName||`media-${Date.now()}`, (a.mimeType||"image/jpeg").startsWith("video/")?"video":"image")}
 async function pickFile(){const x=await DocumentPicker.getDocumentAsync({copyToCacheDirectory:true});if(x.canceled)return;const a=x.assets[0];await uploadUri(a.uri,a.mimeType||"application/octet-stream",a.name,"file")}
 async function uploadUri(uri:string,mime:string,name0:string,type:"image"|"video"|"file"){if(!supabase||!cid||!me)return; setMediaBusy(true); try{const path=`${cid}/${me}/${Date.now()}-${name0.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const res=await fetch(uri);const buf=await res.arrayBuffer();const up=await supabase.storage.from("chat-media").upload(path,buf,{contentType:mime,upsert:false});if(up.error)throw up.error;await send(name0,type,path)}catch(e:any){Alert.alert("Upload failed",e.message||"Could not upload file")}finally{setMediaBusy(false)}}
 async function openMedia(path:string){if(!supabase)return;const {data,error}=await supabase.storage.from("chat-media").createSignedUrl(path,60*60);if(error)return Alert.alert("Media unavailable",error.message);await Linking.openURL(data.signedUrl)}
 async function startCall(kind:"voice"|"video"){if(!supabase||!cid||!profileId)return;const {data,error}=await supabase.rpc("create_call_session",{p_conversation_id:cid,p_callee_id:profileId,p_kind:kind});if(error)return Alert.alert("Call failed",error.message);router.push({pathname:"/call",params:{callId:data,otherId:profileId,name,kind}})}
 return <View style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={s.name}>{name||"Group chat"}</Text><Text style={s.online}>{typing?"typing…":"Private chat"}</Text></View><View style={{flexDirection:"row",gap:14,marginLeft:"auto"}}>{profileId&&<><Pressable onPress={()=>startCall("voice")}><Text style={s.headIcon}>📞</Text></Pressable><Pressable onPress={()=>startCall("video")}><Text style={s.headIcon}>🎥</Text></Pressable></>}</View></View>
 {loading?<View style={s.center}><ActivityIndicator color={theme.purple}/><Text style={s.muted}>Opening secure chat…</Text></View>:<FlatList data={messages} keyExtractor={x=>x.id} contentContainerStyle={{padding:16,paddingBottom:100}} renderItem={({item})=>{const mine=item.sender_id===me;return <View style={[s.row,mine&&s.mine]}><View style={[s.bubble,mine&&s.myBubble]}>{item.message_type!=="text"&&item.media_url?<MediaBubble path={item.media_url} type={item.message_type} onOpen={()=>openMedia(item.media_url)}/>:<Text style={s.msg}>{item.body}</Text>}<Text style={s.time}>{new Date(item.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}{mine?(item.read_at?"  ✓✓":"  ✓"):""}</Text></View></View>}}/>}
 <View style={s.tools}><Pressable onPress={pickImage} disabled={mediaBusy}><Text style={s.tool}>＋</Text></Pressable><Pressable onPress={pickFile} disabled={mediaBusy}><Text style={s.tool}>📎</Text></Pressable><TextInput style={s.field} placeholder={mediaBusy?"Uploading…":"Message…"} placeholderTextColor={theme.muted} value={text} onChangeText={setText} onSubmitEditing={()=>send()} /><Pressable style={s.send} onPress={()=>send()}><Text style={s.sendText}>➤</Text></Pressable></View></View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg,paddingTop:45},header:{height:70,paddingHorizontal:18,flexDirection:"row",alignItems:"center",gap:14,borderBottomWidth:1,borderBottomColor:theme.border},back:{color:"#fff",fontSize:35},name:{color:"#fff",fontSize:17,fontWeight:"800"},online:{color:theme.success,fontSize:11,marginTop:3},headIcon:{fontSize:21},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10},muted:{color:theme.muted},row:{alignItems:"flex-start"},mine:{alignItems:"flex-end"},bubble:{alignSelf:"flex-start",backgroundColor:theme.card2,borderRadius:16,padding:12,marginBottom:8,maxWidth:"82%"},myBubble:{backgroundColor:theme.purple},msg:{color:"#fff",fontSize:15},time:{color:"#c8cff4",fontSize:9,marginTop:5,alignSelf:"flex-end"},image:{width:220,height:220,borderRadius:12,backgroundColor:theme.card},attachment:{minWidth:190},file:{color:"#fff",fontSize:14,fontWeight:"700"},fileName:{color:"#fff",marginTop:5},open:{color:"#d8ccff",fontSize:11,marginTop:6},tools:{position:"absolute",left:10,right:10,bottom:10,flexDirection:"row",gap:7,alignItems:"center"},tool:{color:"#fff",fontSize:24,width:32,textAlign:"center"},field:{flex:1,height:50,borderRadius:18,borderWidth:1,borderColor:theme.border,backgroundColor:theme.card,color:"#fff",paddingHorizontal:15},send:{width:50,height:50,borderRadius:25,backgroundColor:theme.purple,alignItems:"center",justifyContent:"center"},sendText:{color:"#fff",fontSize:21}});
