import { useEffect, useState } from "react";
import { View, Text, TextInput, Pressable, FlatList, StyleSheet, Alert } from "react-native";
import { router } from "expo-router";
import { supabase } from "@/lib/supabase"; import { theme } from "@/lib/theme";
export default function Groups(){const [users,setUsers]=useState<any[]>([]);const [selected,setSelected]=useState<string[]>([]);const [title,setTitle]=useState("");const [q,setQ]=useState("");
 useEffect(()=>{(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user)return;const {data}=await supabase.from("profiles").select("id,username,display_name").neq("id",user.id).limit(100);setUsers(data||[])})()},[]);
 const visible=users.filter(x=>(x.username||"").toLowerCase().includes(q.toLowerCase())||(x.display_name||"").toLowerCase().includes(q.toLowerCase()));
 async function create(){if(!supabase||!title.trim())return Alert.alert("Group name required");const {data,error}=await supabase.rpc("create_group",{p_title:title.trim(),p_members:selected});if(error)return Alert.alert("Group failed",error.message);router.replace({pathname:"/chat",params:{conversationId:data,name:title.trim()}})}
 return <View style={s.root}><View style={s.head}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><Text style={s.title}>New group</Text></View><TextInput value={title} onChangeText={setTitle} placeholder="Group name" placeholderTextColor={theme.muted} style={s.input}/><TextInput value={q} onChangeText={setQ} placeholder="Search people" placeholderTextColor={theme.muted} style={s.input}/><FlatList data={visible} keyExtractor={x=>x.id} renderItem={({item})=><Pressable style={s.user} onPress={()=>setSelected(a=>a.includes(item.id)?a.filter(v=>v!==item.id):[...a,item.id])}><View style={s.avatar}><Text style={s.avatarText}>{(item.display_name||item.username)[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{item.display_name||item.username}</Text><Text style={s.muted}>@{item.username}</Text></View><Text style={s.check}>{selected.includes(item.id)?"✓":"○"}</Text></Pressable>}/><Pressable style={s.create} onPress={create}><Text style={s.createText}>Create group ({selected.length})</Text></Pressable></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg,padding:20,paddingTop:50},head:{flexDirection:"row",alignItems:"center",gap:12,marginBottom:18},back:{color:"#fff",fontSize:35},title:{color:"#fff",fontSize:24,fontWeight:"800"},input:{height:50,borderRadius:16,borderWidth:1,borderColor:theme.border,backgroundColor:theme.card,color:"#fff",paddingHorizontal:15,marginBottom:10},user:{flexDirection:"row",alignItems:"center",gap:12,paddingVertical:12,borderBottomWidth:1,borderBottomColor:theme.border},avatar:{width:48,height:48,borderRadius:16,backgroundColor:theme.card2,alignItems:"center",justifyContent:"center"},avatarText:{color:"#fff",fontSize:18,fontWeight:"800"},name:{color:"#fff",fontWeight:"700"},muted:{color:theme.muted,fontSize:12,marginTop:3},check:{color:theme.purple,fontSize:25},create:{position:"absolute",bottom:20,left:20,right:20,height:52,borderRadius:20,backgroundColor:theme.purple,alignItems:"center",justifyContent:"center"},createText:{color:"#fff",fontWeight:"800"}});
