import { useEffect, useState } from "react";
import { View, Text, StyleSheet, Pressable, FlatList, ActivityIndicator } from "react-native";
import { theme } from "@/lib/theme";
import { router } from "expo-router";
import { supabase } from "@/lib/supabase";

export default function Home() {
 const [tab,setTab]=useState("Chats"),[filter,setFilter]=useState("All"),[favorites,setFavorites]=useState<string[]>([]),[chats,setChats]=useState<any[]>([]),[loading,setLoading]=useState(true);
 async function load(){if(!supabase){setLoading(false);return} const {data,error}=await supabase.rpc("get_my_chats");if(!error)setChats(data||[]);const {data:me}=await supabase.auth.getUser();if(me.user){const {data:f}=await supabase.from("favorite_contacts").select("contact_id").eq("user_id",me.user.id);setFavorites((f||[]).map((x:any)=>x.contact_id))}setLoading(false)}
 useEffect(()=>{let ch:any;(async()=>{if(!supabase)return;const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/login");return}await load();ch=supabase.channel(`home-${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"messages"},load).on("postgres_changes",{event:"INSERT",schema:"public",table:"call_sessions",filter:`callee_id=eq.${user.id}`},async({new:c}:any)=>{if(c.status!=="ringing")return;const {data:p}=await supabase.from("profiles").select("display_name,username").eq("id",c.caller_id).single();router.push({pathname:"/call",params:{callId:c.id,name:p?.display_name||p?.username||"bs.world user",kind:c.kind,incoming:"1"}})}).subscribe()})();return()=>{if(ch&&supabase)supabase.removeChannel(ch)}},[]);
 const shown=chats.filter(x=>filter==="All"||(filter==="Unread"&&x.unread_count>0)||(filter==="Groups"&&x.kind==="group")||(filter==="Favorites"&&favorites.includes(x.other_user_id)));
 function openChat(item:any){if(item.kind==="group")router.push({pathname:"/chat",params:{conversationId:item.conversation_id,name:item.title||"Group"}});else router.push({pathname:"/chat",params:{profileId:item.other_user_id,name:item.other_display_name||item.other_username}})}
 return <View style={styles.root}><View style={styles.header}><View><Text style={styles.brand}>bs<Text style={styles.dot}>.</Text>world</Text><Text style={styles.sub}>Connect. Share. Belong.</Text></View><Pressable onPress={()=>router.push("/contacts")}><Text style={styles.icon}>⌕</Text></Pressable></View><View style={styles.stories}><Pressable style={styles.story} onPress={()=>router.push("/contacts")}><View style={styles.avatar}><Text style={styles.avatarText}>＋</Text></View><Text style={styles.storyText}>New chat</Text></Pressable><Pressable style={styles.story} onPress={()=>router.push("/groups")}><View style={styles.avatar}><Text style={styles.avatarText}>👥</Text></View><Text style={styles.storyText}>New group</Text></Pressable></View><View style={styles.filters}>{["All","Unread","Groups","Favorites"].map(x=><Pressable key={x} onPress={()=>setFilter(x)} style={[styles.filter,filter===x&&styles.active]}><Text style={styles.filterText}>{x}</Text></Pressable>)}</View>{loading?<View style={styles.center}><ActivityIndicator color={theme.purple}/><Text style={styles.muted}>Loading chats…</Text></View>:<FlatList data={shown} keyExtractor={x=>x.conversation_id} contentContainerStyle={{paddingBottom:100}} ListEmptyComponent={<View style={styles.center}><Text style={styles.muted}>No chats yet. Open Contacts to start one.</Text></View>} renderItem={({item})=><Pressable style={styles.chat} onPress={()=>openChat(item)}><View style={styles.avatar}><Text style={styles.avatarText}>{item.kind==="group"?"👥":(item.other_display_name||item.other_username||"U")[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={styles.name}>{item.kind==="group"?(item.title||"Group"):(item.other_display_name||item.other_username)}</Text><Text style={styles.msg}>{item.last_message_type&&item.last_message_type!=="text"?"Attachment":item.last_body||"Start a conversation"}</Text></View><View style={{alignItems:"flex-end"}}>{item.last_created_at&&<Text style={styles.time}>{new Date(item.last_created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</Text>}{item.unread_count>0&&<View style={styles.badge}><Text style={styles.badgeText}>{item.unread_count}</Text></View>}</View></Pressable>}/>}<View style={styles.bottom}>{["Chats","Calls","＋","Contacts","Profile"].map(x=><Pressable key={x} onPress={()=>{setTab(x);if(x==="Contacts")router.replace("/contacts");else if(x==="Profile")router.replace("/profile");else if(x==="Calls")router.replace("/calls");else if(x==="＋")router.push("/groups")}} style={styles.nav}><Text style={[styles.navIcon,x==="＋"&&styles.plus]}>{x==="＋"?"＋":x==="Chats"?"▣":x==="Calls"?"⌕":x==="Contacts"?"♙":"●"}</Text><Text style={[styles.navText,tab===x&&styles.selected]}>{x}</Text></Pressable>)}</View></View>
}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:theme.bg,paddingTop:52},header:{paddingHorizontal:20,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},brand:{fontSize:25,fontWeight:"800",color:theme.text},dot:{color:theme.purple},sub:{color:theme.muted,fontSize:11,marginTop:2},icon:{color:"#fff",fontSize:25},stories:{flexDirection:"row",padding:18,gap:15},story:{alignItems:"center"},avatar:{width:54,height:54,borderRadius:18,backgroundColor:theme.card2,borderWidth:1,borderColor:theme.purple,alignItems:"center",justifyContent:"center"},avatarText:{fontSize:21,fontWeight:"700",color:"#fff"},storyText:{fontSize:11,color:theme.muted,marginTop:5},filters:{flexDirection:"row",paddingHorizontal:18,gap:8,marginBottom:4},filter:{paddingHorizontal:15,paddingVertical:8,borderRadius:18,backgroundColor:theme.card},active:{backgroundColor:theme.purple},filterText:{color:"#fff",fontSize:12},chat:{flexDirection:"row",alignItems:"center",paddingHorizontal:20,paddingVertical:14,gap:12},name:{color:"#fff",fontWeight:"700",fontSize:15},msg:{color:theme.muted,marginTop:4},time:{color:theme.muted,fontSize:11},badge:{marginTop:7,minWidth:20,height:20,borderRadius:10,backgroundColor:theme.purple,alignItems:"center",justifyContent:"center"},badgeText:{color:"#fff",fontSize:11,fontWeight:"700"},center:{flex:1,alignItems:"center",justifyContent:"center",gap:10,padding:20},muted:{color:theme.muted,textAlign:"center"},bottom:{position:"absolute",bottom:0,left:0,right:0,height:78,backgroundColor:"#0B1035",borderTopWidth:1,borderTopColor:theme.border,flexDirection:"row",justifyContent:"space-around",alignItems:"center"},nav:{alignItems:"center",minWidth:55},navIcon:{fontSize:21,color:theme.muted},plus:{backgroundColor:theme.purple,color:"#fff",width:52,height:52,borderRadius:26,textAlign:"center",textAlignVertical:"center",fontSize:31,marginTop:-30},navText:{fontSize:10,color:theme.muted,marginTop:4},selected:{color:"#fff",fontWeight:"700"}});
